<div class="profile">
    <a class="client-name profile-button" href="/carts"><img class="profile-icon" width="20" height="19" src="https://img.freepik.com/free-icon/shopping-cart-of-checkered-design_318-50865.jpg" alt="">
        <?php echo $profileEmail; ?></a>
    <a class="profile-exit profile-button" href="/logout"><svg class="profile-icon" width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 9L11.125 0.5V6.5H5.125V11.5H11.125V17.5L20 9Z" fill="#C5C5C5"></path><path d="M2.10601 14.452V3.548C2.12401 3.172 2.27701 2.491 3.11601 2.491H8.14301V0.5H3.11601C0.938006 0.5 0.112006 2.31 0.0870056 3.527V14.473C0.112006 15.689 0.938006 17.5 3.11601 17.5H8.14301V15.51H3.11601C2.27701 15.51 2.12401 14.827 2.10601 14.452Z" fill="#C5C5C5"></path></svg></a>
</div>

<div class="container">
    <h3>Каталог</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
        <form action="/add-product" method="POST">
            <div class="card text-center">
                <a href="">
                    <div class="card-header">
                        Hit!
                    </div>
                    <img class="card-img-top" width="300" height="400" src="<?php echo $product['image_url']; ?>" alt="Card image">
                    <div class="card-body">
                        <input type="text" name="product_id" hidden="true" value="<?php echo $product['id']; ?>">
                        <p class="card-text text-muted">
                            <?php echo $product['name'];?>
                            <a href=""><h5 class="card-title"><?php echo $product['description'];?></h5></a>
                        <div class="card-footer">
                            <?php echo $product['price'] . ' руб.';?>
                        </div>
                    </div>
                    <button type="submit">Добавить в корзину</button>
                </a>
            </div>
        </form>
        <?php endforeach; ?>
    </div>
</div>


<style>

    body {
        background-color: #f6f7f8;
    }

    /* основные стили */
    .profile {
        display: flex;
        float: right;
    }

    /* общие стили для всех кнопок авторизации, включая кнопки входа, корорые были на макете главной */
    .profile-button {
        background-color: #faf8f8;
        padding: 12px;
        font-size: 21px;
        line-height: 21px;
        text-decoration: none;
        color: #000;
        display: flex;
        align-items: center;
    }

    .profile-button:hover .profile-icon path{
        fill: #3d546f;
    }

    .profile-button:active {
        color: #c5c5c5;
    }

    .profile-button:active .profile-icon path{
        fill: #da1010;
    }

    /* стили отдельных элементов */
    .client-name {
        padding-left: 15px;
        padding-right: 10px;
    }

    .client-name .profile-icon {
        margin-right: 21px;
    }

    .profile-exit {
        padding-right: 10px;
        padding-left: 17px;
    }

    body {
        font-style: normal;
    }

    a {
        text-decoration: none;
        font-size: 23px;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
        text-align: center;
        color: #2a2621;
        font-size: 30px;
        font-style: italic;
        padding-top: 90px;
    }

    .card {
        float: left; /*Задаем обтекание*/
        margin-right: 20px;
        margin-left: 35px;


    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: #e89a38;
        background-color: white;
    }

    .text-muted {
        font-size: 22px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: #6dc718;
    }

</style>