<?php

session_start();
if (!isset($_SESSION['user'])) {
    header('Location: /login');
}

?>

<div class="profile">
    <a class="client-name profile-button" href=""><svg class="profile-icon" width="20" height="19" viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.881 14.666C15.737 13.931 13.625 13 12.674 12.276C12.017 11.775 11.904 10.658 12.157 9.861C13.275 8.958 14.021 7.384 14.021 5.583C14.021 2.776 12.221 0.5 10 0.5C7.77902 0.5 5.97901 2.776 5.97901 5.583C5.97901 7.384 6.72501 8.957 7.84201 9.86C8.09501 10.658 7.98302 11.775 7.32502 12.276C6.37502 13 4.26201 13.93 2.11801 14.666C-0.0259852 15.402 1.48343e-05 18.5 1.48343e-05 18.5H20C20 18.5 20.025 15.401 17.881 14.666Z" fill="#C5C5C5"></path></svg>
        <?php echo $_SESSION['user']['email']; ?></a>
    <a class="profile-exit profile-button" href="/logout"><svg class="profile-icon" width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 9L11.125 0.5V6.5H5.125V11.5H11.125V17.5L20 9Z" fill="#C5C5C5"></path><path d="M2.10601 14.452V3.548C2.12401 3.172 2.27701 2.491 3.11601 2.491H8.14301V0.5H3.11601C0.938006 0.5 0.112006 2.31 0.0870056 3.527V14.473C0.112006 15.689 0.938006 17.5 3.11601 17.5H8.14301V15.51H3.11601C2.27701 15.51 2.12401 14.827 2.10601 14.452Z" fill="#C5C5C5"></path></svg></a>
</div>

<style>
    /* рандомный стиль, чтобы выделить кнопку */
    body {
        background-color: #f6f7f8;
    }

    /* основные стили */
    .profile {
        display: flex;
    }

    /* общие стили для всех кнопок авторизации, включая кнопки входа, корорые были на макете главной */
    .profile-button {
        background-color: #faf8f8;
        padding: 12px 0;
        font-size: 21px;
        line-height: 21px;
        text-decoration: none;
        color: #000;
        display: flex;
        align-items: center;
    }

    .profile-button:hover .profile-icon path{
        fill: #3d546f;
    }

    .profile-button:active {
        color: #c5c5c5;
    }

    .profile-button:active .profile-icon path{
        fill: #da1010;
    }

    /* стили отдельных элементов */
    .client-name {
        padding-left: 15px;
        padding-right: 10px;
    }

    .client-name .profile-icon {
        margin-right: 21px;
    }

    .profile-exit {
        padding-right: 10px;
        padding-left: 17px;
    }

</style>